"""extend interactions schema per mockup

Revision ID: 00128f3ace83
Revises: 6ca8f883c2e5
Create Date: 2026-07-14 15:38:26.351697

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00128f3ace83"
down_revision: str | Sequence[str] | None = "6ca8f883c2e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interactions", sa.Column("interaction_type", sa.String(), nullable=False)
    )
    op.add_column(
        "interactions",
        sa.Column(
            "attendees",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "interactions", sa.Column("topics_discussed", sa.String(), nullable=True)
    )
    op.add_column(
        "interactions",
        sa.Column(
            "materials_shared",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "interactions",
        sa.Column(
            "samples_distributed",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("interactions", sa.Column("sentiment", sa.String(), nullable=True))
    op.add_column("interactions", sa.Column("outcomes", sa.String(), nullable=True))
    op.add_column(
        "interactions", sa.Column("follow_up_notes", sa.String(), nullable=True)
    )
    op.add_column("interactions", sa.Column("source", sa.String(), nullable=False))
    op.add_column(
        "interactions",
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    )
    op.drop_column("interactions", "channel")
    op.drop_column("interactions", "notes")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interactions",
        sa.Column("notes", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "interactions",
        sa.Column("channel", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("interactions", "is_active")
    op.drop_column("interactions", "source")
    op.drop_column("interactions", "follow_up_notes")
    op.drop_column("interactions", "outcomes")
    op.drop_column("interactions", "sentiment")
    op.drop_column("interactions", "samples_distributed")
    op.drop_column("interactions", "materials_shared")
    op.drop_column("interactions", "topics_discussed")
    op.drop_column("interactions", "attendees")
    op.drop_column("interactions", "interaction_type")
    # ### end Alembic commands ###
