"""add follow_ups table

Revision ID: 29fab75ee5fb
Revises: 00128f3ace83
Create Date: 2026-07-14 17:16:29.304485

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "29fab75ee5fb"
down_revision: str | Sequence[str] | None = "00128f3ace83"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follow_ups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("interaction_id", sa.UUID(), nullable=True),
        sa.Column("hcp_id", sa.UUID(), nullable=False),
        sa.Column("rep_id", sa.UUID(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column("status", sa.String(), server_default="open", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["hcp_id"],
            ["hcps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["interaction_id"],
            ["interactions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["rep_id"],
            ["reps.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("follow_ups")
    # ### end Alembic commands ###
