"""add hcps.is_active

Revision ID: 6ca8f883c2e5
Revises: e7ad8453c9d9
Create Date: 2026-07-14 15:17:36.014388

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ca8f883c2e5"
down_revision: str | Sequence[str] | None = "e7ad8453c9d9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hcps",
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("hcps", "is_active")
    # ### end Alembic commands ###
