"""add compliance flags to interactions

Revision ID: 8edcba5a1e14
Revises: 29fab75ee5fb
Create Date: 2026-07-14 17:34:59.963766

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8edcba5a1e14"
down_revision: str | Sequence[str] | None = "29fab75ee5fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "interactions",
        sa.Column(
            "compliance_flags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "interactions",
        sa.Column(
            "has_compliance_flags", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    op.create_index(
        op.f("ix_interactions_has_compliance_flags"),
        "interactions",
        ["has_compliance_flags"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_interactions_has_compliance_flags"), table_name="interactions"
    )
    op.drop_column("interactions", "has_compliance_flags")
    op.drop_column("interactions", "compliance_flags")
    # ### end Alembic commands ###
